apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: seatunnel-spark-example
spec:
  type: Java
  mode: cluster
  image: docker.io/library/seatunnel:2.3.3-spark-3.3.3
  imagePullPolicy: Never
  mainClass: org.apache.seatunnel.core.starter.spark.SeaTunnelSpark
  mainApplicationFile: "local:///opt/seatunnel/starter/seatunnel-spark-3-starter.jar"
  arguments: ["--config", "/data/seatunnel.batch.conf"]
  sparkVersion: "3.3.3"
  restartPolicy:
    type: Never
  volumes:
    - name: seatunnel-config
      configMap:
        name: seatunnel-config
        items:
        - key: seatunnel.batch.conf
          path: seatunnel.batch.conf
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.3.3
    serviceAccount: spark
    volumeMounts:
      - name: seatunnel-config
        mountPath: /data
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.3.3
    volumeMounts:
      - name: seatunnel-config
        mountPath: /data