version: '3'
services:
  seatunnel-engine:
    build:
      dockerfile: engine.Dockerfile
    ports:
      - "5801:5801"
    environment:
      - config=/data/seatunnel.streaming.conf
    volumes:
      - ./seatunnel.streaming.conf:/data/seatunnel.streaming.conf
    networks:
      - seatunnel

  backend:
    build:
      dockerfile: backend.Dockerfile
    ports:
      - "8801:8801"
    networks:
      - seatunnel

  frontend:
    build:
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:5173"
    networks:
      - seatunnel

networks:
  seatunnel:
    driver: bridge